name: advantages
schema:
  servicie:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: service
      referenceTitleField: title
      showOnGrid: false
      gridFiltering: false
  title:
    type: string
    multilingual: true
    uiParams:
      required: false
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  description:
    type: string
    multilingual: true
    uiParams:
      required: false
      component: input
      inputType: text
      order: 1
      showOnGrid: false
uiParams:
  component: post-table
  ordering: true
  nameField: title
