name: ahc
schema:
  title:
    type: string
    multilingual: true
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  description:
    type: string
    multilingual: true
    uiParams:
      component: editor
      inputType: text
      order: 1
      showOnGrid: true
  image:
    multilingual: true
    type: file
    allowedTypes: [ "jpg", "jpeg", "png" ]
    uiParams:
      required: true
      multiple: false
      component: file
      type: image
  url:
    type: string
    multilingual: true
    uiParams:
      component: slug
      autoGenerateFrom: title
      order: 1
uiParams:
  component: post-table
