name: blogs
schema:
  title:
    type: string
    multilingual: true
    uiParams:
      required: false
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  date:
    required: false
    type: date
    filtering: RANGE
    uiParams:
      component: date-picker
      order: 1
      showOnGrid: true
  desctiption:
    type: string
    multilingual: true
    uiParams:
      required: false
      component: editor
      inputType: text
      order: 2
  content:
    required: false
    multilingual: true
    type: string
    uiParams:
      component: editor
      order: 1
  url:
    type: string
    multilingual: true
    uiParams:
      component: slug
      inputType: text
      autoGenerateFrom: title
      order: 1
  meta-description:
    multilingual: true
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
  keyword:
    multilingual: true
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
  file:
    type: file
    allowedTypes: [ "jpg", "jpeg", "png" ]
    uiParams:
      component: file
      required: false
      multiple: false
      type: image
      order: 2
uiParams:
  component: post-table
