name: company-view
schema:
  preview-image:
    type: file
    allowedTypes: [ "jpg", "jpeg", "png" ]
    uiParams:
      component: file
      required: false
      multiple: true
      type: image
      order: 2
uiParams:
  component: single-page
  singular: true
