name: company-view
schema:
  title:
    multilingual: true
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  preview-image:
    type: file
    allowedTypes: [ "jpg", "jpeg", "png" ]
    uiParams:
      component: file
      required: false
      multiple: false
      type: image
      order: 2
  youtube-link:
    type: string
    uiParams:
      component: input
      order: 3
uiParams:
  component: post-table
