name: gallery
schema:
  image:
    type: file
    allowedTypes: [ "jpg", "jpeg", "png" ]
    uiParams:
      component: file
      required: false
      multiple: false
      type: image
      order: 2
uiParams:
  component: post-table
