name: logo
schema:
  title:
    type: string
    multilingual: true
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  preview-logo:
    multilingual: false
    type: file
    allowedTypes: [ "jpg", "jpeg", "png" ]
    uiParams:
      required: true
      multiple: false
      component: file
      type: image
  original-logo:
    multilingual: false
    type: file
    allowedTypes: [ "zip" ]
    uiParams:
      required: true
      multiple: false
      component: file
      type: raw
  rules:
    multilingual: false
    type: file
    allowedTypes: [ "pdf" ]
    uiParams:
      required: true
      multiple: false
      component: file
      type: raw
uiParams:
  component: post-table
