name: pictures
schema:
  bulk-image:
    type: file
    allowedTypes: [ "jpg", "jpeg", "png" ]
    uiParams:
      required: false
      multiple: true
      component: file
      type: image
uiParams:
  component: post-table
