name: terminalogy
schema:
  title:
    multilingual: true
    required: false
    type: string
    uiParams:
      showOnGrid: true
      component: input
      order: 1
  content:
    multilingual: true
    required: false
    type: string
    uiParams:
      component: editor
      order: 1
uiParams:
  component: post-table
