name: trainer
schema:
  fullname:
    type: string
    multilingual: true
    uiParams:
      showOnGrid: true
      required: false
      component: input
      inputType: text
      order: 1
  position:
    type: string
    multilingual: true
    uiParams:
      showOnGrid: true
      required: false
      component: input
      inputType: text
      order: 1
  content:
    multilingual: true
    required: false
    type: string
    uiParams:
      component: editor
      order: 1
  linkedin:
    type: string
    multilingual: false
    uiParams:
      showOnGrid: false
      required: false
      component: input
      inputType: text
      order: 1
  facebook:
    type: string
    multilingual: false
    uiParams:
      showOnGrid: true
      required: false
      component: input
      inputType: text
      order: 1
  instagram:
    type: string
    multilingual: false
    uiParams:
      required: false
      component: input
      inputType: text
      order: 1
  image:
    type: image
    allowedTypes: [ "jpg", "jpeg", "png" ]
    uiParams:
      component: file
      required: false
      multiple: false
      type: image
      order: 2
  showOnIndex:
    type: boolean
    uiParams:
      component: checkbox
      order: 2
  url:
    multilingual: true
    type: string
    uiParams:
      component: slug
      autoGenerateFrom: fullname
      order: 1
      showOnGrid: true
uiParams:
  component: post-table
