name: hobby
schema:
  title:
    multilingual: true
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  hobby-type:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: hobby-type
      referenceTitleField: title
      showOnGrid: true
      gridFiltering: true
uiParams:
  component: post-table
