name: index-settings
schema:
  fullname:
    type: string
    multilingual: true
    uiParams:
      showOnGrid: true
      required: false
      component: input
      inputType: text
      order: 1
  job-title:
    type: string
    multilingual: true
    uiParams:
      showOnGrid: true
      required: false
      component: input
      inputType: text
      order: 1
  image:
    type: file
    allowedTypes: [ "jpg", "jpeg", "png" ]
    uiParams:
      component: file
      required: true
      multiple: false
      type: image
      order: 2
  gained-success:
    type: string
    uiParams:
      required: false
      component: input
      inputType: text
      order: 1
  experience:
    type: string
    uiParams:
      required: false
      component: input
      inputType: text
      order: 1
  published-book:
    type: string
    uiParams:
      required: false
      component: input
      inputType: text
      order: 1
  printed-article:
    type: string
    uiParams:
      required: false
      component: input
      inputType: text
      order: 1
uiParams:
  component: single-page
  singular: true
