name: success-certificate
schema:
  title:
    multilingual: true
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  url:
    multilingual: true
    type: string
    uiParams:
      component: slug
      autoGenerateFrom: title
      order: 1
      showOnGrid: true
  image:
    type: file
    allowedTypes: [ "jpg", "jpeg", "png" ]
    uiParams:
      component: file
      required: true
      multiple: false
      type: image
      order: 2
  success-certificate-type:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: success-certificate-type
      referenceTitleField: title
      showOnGrid: true
      gridFiltering: true
uiParams:
  component: post-table
