name: about
schema:
  title:
    type: string
    multilingual: true
    uiParams:
      showOnGrid: true
      required: false
      component: input
      inputType: text
      order: 1
  content:
    multilingual: true
    required: false
    type: string
    uiParams:
      component: editor
      order: 1
  url:
    type: string
    uiParams:
      component: slug
      autoGenerateFrom: title
      order: 1
uiParams:
  component: post-table
