name: anouncement1
schema:
  vacancy:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: vacancy-anouncement
      referenceTitleField: title
      showOnGrid: true
  company:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: company-anouncement
      referenceTitleField: title
      showOnGrid: true
  category:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: category-anouncement
      referenceTitleField: title
      showOnGrid: true
  city:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: city-anouncement
      referenceTitleField: title
      showOnGrid: true
  start-date:
    type: date
    filtering: RANGE
    uiParams:
      component: date-picker
      order: 1
      showOnGrid: true
  end-date:
    type: date
    filtering: RANGE
    uiParams:
      component: date-picker
      order: 1
      showOnGrid: true
  content:
    multilingual: true
    type: string
    uiParams:
      component: editor
      order: 3
  new:
    type: boolean
    uiParams:
      component: checkbox
      order: 2
  premium:
    type: boolean
    uiParams:
      component: checkbox
      order: 2
  pin:
    type: boolean
    uiParams:
      component: checkbox
      order: 2
uiParams:
  component: post-table
