name: faq
schema:
  question:
    multilingual: true
    type: string
    uiParams:
      showOnGrid: true
      component: editor
      order: 1
  answer:
    multilingual: true
    type: string
    uiParams:
      component: editor
      order: 1
uiParams:
  component: post-table
