name: faq
schema:
  question:
    multilingual: true
    type: string
    uiParams:
      component: input
      inputType: editor
      order: 1
  answer:
    multilingual: true
    type: string
    uiParams:
      component: input
      inputType: editor
      order: 1
uiParams:
  component: post-table