name: footer-menu
schema:
  name:
    multilingual: true
    type: string
    uiParams:
      component: text
      order: 3
  key:
    type: string
    uiParams:
      component: text
      order: 3
uiParams:
  component: post-table
