name: page
schema:
  title:
    type: string
    multilingual: true
    uiParams:
      showOnGrid: true
      required: false
      component: input
      inputType: text
      order: 1
  content:
    multilingual: true
    required: false
    type: string
    uiParams:
      component: editor
      order: 1
  url:
    type: string
    uiParams:
      component: slug
      autoGenerateFrom: title
      order: 1
  metaDescription:
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
  keyword:
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
  showInAboutPage:
    type: boolean
    uiParams:
      component: checkbox
      order: 2
uiParams:
  component: post-table
