name: partners
schema:
  enabled:
    type: boolean
    uiParams:
      component: checkbox
      order: 2
  name:
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
  preview-logo:
    type: image
    allowedTypes: [ "jpg", "jpeg", "png" ]
    uiParams:
      component: image-upload
      order: 2
  url-for-image:
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
uiParams:
  component: post-table
