name: partners
schema:
  title:
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
  enabled:
    type: boolean
    uiParams:
      component: checkbox
      order: 2
  name:
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
  surname:
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
  position:
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
  profile-image:
    type: image
    allowedTypes: [ "jpg", "jpeg", "png" ]
    uiParams:
      component: image-upload
      order: 2
uiParams:
  component: post-table
