name: service
schema:
  title:
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
  slug:
    type: string
    uiParams:
      component: slug
      autoGenerateFrom: title
      order: 2
  content:
    type: string
    uiParams:
      component: editor
      order: 3
  desctription:
    type: string
    uiParams:
      component: text-area
  keywords:
    type: string
    uiParams:
      component: text-area
uiParams:
  component: post-table
