name: settings
schema:
  email:
    type: string
    multilingual: false
    uiParams:
      showOnGrid: true
      required: false
      component: input
      inputType: text
      order: 1
  phone:
    type: string
    multilingual: false
    uiParams:
      showOnGrid: true
      required: false
      component: input
      inputType: text
      order: 1
  adress:
    type: string
    multilingual: false
    uiParams:
      showOnGrid: true
      required: false
      component: input
      inputType: text
      order: 1
uiParams:
  component: single-page
  singular: true
