name: settings
schema:
  contactEmail:
    type: string
    uiParams:
      showOnGrid: true
      required: false
      component: input
      inputType: text
      order: 1
      tab: email-config
  registerEmail:
    type: string
    uiParams:
      required: false
      component: input
      inputType: text
      order: 1
      tab: email-config
      showOnGrid: true
  facebookUrl:
    type: string
    uiParams:
      required: false
      component: input
      inputType: text
      order: 1
      tab: social
  instagramUrl:
    type: string
    uiParams:
      required: false
      component: input
      inputType: text
      order: 1
      tab: social
uiParams:
  component: single-page
  singular: true
