name: anouncement-type
schema:
  title:
    multilingual: true
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
uiParams:
  component: post-table
