name: anouncement
schema:
  status:
    type: enum-select
    uiParams:
      required: true
      component: enum-select
      showOnGrid: true
      enum:
        - PENDING
        - PUBLISHED
        - REJECTED
      langName: announcement-status
  is-vip:
    type: boolean
    uiParams:
      component: checkbox
      order: 2
  announcement-type:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: anouncement-type
      referenceTitleField: title
      showOnGrid: true
      gridFiltering: true
  announcement-object-type:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: anouncement-object-type
      referenceTitleField: title
      showOnGrid: true
      gridFiltering: true
  provience:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: provience
      referenceTitleField: title
      showOnGrid: true
      gridFiltering: true
  marker:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: marker
      referenceTitleField: title
      showOnGrid: true
      gridFiltering: true
  metro:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: metro
      referenceTitleField: title
      showOnGrid: true
      gridFiltering: true
  merchant:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: merchant
      referenceTitleField: fullname
      showOnGrid: true
      gridFiltering: true
  maintenancy-status:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: maintenancy-status
      referenceTitleField: title
      showOnGrid: true
      gridFiltering: true
  rent-or-buy:
    type: boolean
    uiParams:
      component: checkbox
      order: 2
  title:
    multilingual: true
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  price:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  currency:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: currency-type
      referenceTitleField: title
      showOnGrid: true
      gridFiltering: true
  area:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  current-floor:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  total-floors:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  bedroom-count:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  guestroom-count:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  has-barter:
    type: boolean
    uiParams:
      component: checkbox
      order: 2
  has-garage:
    type: boolean
    uiParams:
      component: checkbox
      order: 2
  create-date:
    required: false
    type: date
    filtering: RANGE
    uiParams:
      component: date-picker
      order: 1
      showOnGrid: false
  last-modification-date:
    required: false
    type: date
    filtering: RANGE
    uiParams:
      component: date-picker
      order: 1
      showOnGrid: false
  city:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: city
      referenceTitleField: title
      showOnGrid: false
      gridFiltering: true
  document-type:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: document-type
      referenceTitleField: title
      showOnGrid: false
      gridFiltering: true
  ipotech-type:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: ipotech-type
      referenceTitleField: title
      showOnGrid: false
      gridFiltering: true
  has-internet:
    type: boolean
    uiParams:
      component: checkbox
      order: 2
  description:
    multilingual: true
    type: string
    uiParams:
      component: editor
      inputType: text
      order: 1
      showOnGrid: false
  address:
    multilingual: true
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: false
  map-x:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  map-y:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  images:
    type: file
    allowedTypes: [ "jpg", "jpeg", "png" ]
    uiParams:
      required: false
      multiple: true
      component: file
      type: image
  blueprint:
    type: file
    allowedTypes: [ "jpg", "jpeg", "png" ]
    uiParams:
      required: false
      multiple: false
      component: file
      type: image
uiParams:
  component: post-table
  formComponent: accordion-post
