name: anouncement
schema:
  name:
    multilingual: true
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
      group: group1
  price:
    multilingual: true
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
      group: group1
  area:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
      group: group1
  rooms:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
      group: group1
  date:
    required: false
    type: date
    filtering: RANGE
    uiParams:
      component: date-picker
      order: 1
      showOnGrid: true
      group: group1
  city:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: city
      referenceTitleField: title
      showOnGrid: true
      gridFiltering: true
      group: group1
  type:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: announcement-type
      referenceTitleField: title
      showOnGrid: true
      gridFiltering: true
      group: group2
  document-type:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: document-type
      referenceTitleField: title
      showOnGrid: true
      gridFiltering: true
      group: group2
  floor:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
      group: group2
  map:
    multilingual: false
    type: string
    uiParams:
      component: map
      inputType: text
      order: 1
      showOnGrid: true
      group: group2
  preview:
    type: file
    allowedTypes: [ "jpg", "jpeg", "png" ]
    uiParams:
      component: file
      required: false
      multiple: false
      type: raw
      order: 2
      group: group3
  plan:
    type: file
    allowedTypes: [ "jpg", "jpeg", "png" ]
    uiParams:
      component: file
      required: false
      multiple: false
      type: raw
      order: 2
      group: group3
  content:
    multilingual: true
    type: string
    uiParams:
      component: editor
      inputType: text
      order: 1
      showOnGrid: true
      group: group3
  documented:
    type: boolean
    uiParams:
      component: checkbox
      order: 2
      group: group3
  has-ipotech:
    type: boolean
    uiParams:
      component: checkbox
      order: 2
      group: group3
  has-internet:
    type: boolean
    uiParams:
      component: checkbox
      order: 2
      group: group3
  is-agent:
    type: boolean
    uiParams:
      component: checkbox
      order: 2
      group: group3
  is-vip:
    type: boolean
    uiParams:
      component: checkbox
      order: 2
      group: group3
  has-servicefee:
    type: boolean
    uiParams:
      component: checkbox
      order: 2
      group: group3
  images:
    type: file
    allowedTypes: [ "jpg", "jpeg", "png" ]
    uiParams:
      required: false
      multiple: true
      component: file
      type: image
      group: group3
uiParams:
  component: post-table
  formComponent: accordion-post
