name: anouncement
schema:
  is-vip:
    type: boolean
    uiParams:
      component: checkbox
      order: 2
  type:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: announcement-type
      referenceTitleField: title
      showOnGrid: true
      gridFiltering: true
  merchant:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: merchant
      referenceTitleField: fullname
      showOnGrid: true
      gridFiltering: true
  maintenancy-status:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: maintenancy-status
      referenceTitleField: title
      showOnGrid: true
      gridFiltering: true
  rent-or-buy:
    type: boolean
    uiParams:
      component: checkbox
      order: 2
  title:
    multilingual: true
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  price:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  currency:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: currency-type
      referenceTitleField: title
      showOnGrid: true
      gridFiltering: true
  area:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  current-floor:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  total-floors:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  bedroom-count:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  guestroom-count:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  has-barter:
    type: boolean
    uiParams:
      component: checkbox
      order: 2
  has-garage:
    type: boolean
    uiParams:
      component: checkbox
      order: 2
  create-date:
    required: false
    type: date
    filtering: RANGE
    uiParams:
      component: date-picker
      order: 1
      showOnGrid: true
  last-modification-date:
    required: false
    type: date
    filtering: RANGE
    uiParams:
      component: date-picker
      order: 1
      showOnGrid: true
  city:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: city
      referenceTitleField: title
      showOnGrid: true
      gridFiltering: true
  document-type:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: document-type
      referenceTitleField: title
      showOnGrid: true
      gridFiltering: true
  ipotech-type:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: ipotech-type
      referenceTitleField: title
      showOnGrid: true
      gridFiltering: true
  has-internet:
    type: boolean
    uiParams:
      component: checkbox
      order: 2
  description:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  map-x:
    multilingual: false
    type: string
    uiParams:
      component: map
      inputType: text
      order: 1
      showOnGrid: true
  map-y:
    multilingual: false
    type: string
    uiParams:
      component: map
      inputType: text
      order: 1
      showOnGrid: true
  images:
    type: file
    allowedTypes: [ "jpg", "jpeg", "png" ]
    uiParams:
      required: false
      multiple: true
      component: file
      type: image
  blueprint:
    type: file
    allowedTypes: [ "jpg", "jpeg", "png" ]
    uiParams:
      required: false
      multiple: false
      component: file
      type: image
uiParams:
  component: post-table
  formComponent: accordion-post
