name: anouncement
schema:
  status:
    type: enum-select
    uiParams:
      required: true
      component: enum-select
      showOnGrid: true
      group: 'group1'
      enum:
        - PENDING
        - ACTIVE
        - REJECTED
        - EXPIRED
      langName: announcement-status
  userFullName:
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: false
  remainingPromotionCount:
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: false
  userPhone1:
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: false
  userPhone2:
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: false
  userEmail:
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: false
  user:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: user
      referenceTitleField: email
      showOnGrid: true
      group: 'group1'
      gridFiltering: true
  is-vip:
    type: boolean
    uiParams:
      component: checkbox
      group: 'group1'
      order: 2
  announcement-type:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: anouncement-type
      referenceTitleField: title
      showOnGrid: true
      group: 'group1'
      gridFiltering: true
  office-type:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: office-type
      referenceTitleField: title
      showOnGrid: true
      group: 'group1'
      gridFiltering: true
  office-room-count:
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: false
  adverse-type:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: adverse-type
      referenceTitleField: title
      showOnGrid: false
      group: 'group1'
      gridFiltering: true
  announcement-object-type:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: anouncement-object-type
      referenceTitleField: title
      showOnGrid: true
      group: 'group1'
      gridFiltering: true
  provience:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: provience
      referenceTitleField: title
      showOnGrid: false
      group: 'group1'
      gridFiltering: true
  marker:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: marker
      referenceTitleField: title
      showOnGrid: false
      group: 'group1'
      gridFiltering: true
  metro:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: metro
      referenceTitleField: title
      showOnGrid: false
      gridFiltering: true
      group: 'group1'
  merchant:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: merchant
      referenceTitleField: fullname
      showOnGrid: true
      group: 'group2'
      gridFiltering: true
  maintenancy-status:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: maintenancy-status
      referenceTitleField: title
      showOnGrid: false
      group: 'group2'
      gridFiltering: true
  rent-or-buy:
    type: boolean
    uiParams:
      component: checkbox
      group: 'group2'
      order: 2
  title:
    multilingual: true
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      group: 'group2'
      showOnGrid: true
  price:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: false
      group: 'group2'
  currency:
    type: reference
    uiParams:
      required: false
      component: reference
      postType: currency-type
      referenceTitleField: title
      showOnGrid: false
      group: 'group2'
      gridFiltering: true
  area:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      group: 'group2'
      order: 1
      showOnGrid: false
  current-floor:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      group: 'group2'
      showOnGrid: false
  total-floors:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      group: 'group2'
      showOnGrid: false
  bedroom-count:
    multilingual: false
    type: string
    uiParams:
      component: input
      group: 'group2'
      inputType: text
      order: 1
      showOnGrid: false
  guestroom-count:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      group: 'group2'
      showOnGrid: false
  sanitar-count:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      group: 'group2'
      showOnGrid: false
  has-barter:
    type: boolean
    uiParams:
      component: checkbox
      group: 'group2'
      order: 2
  has-garage:
    type: boolean
    uiParams:
      component: checkbox
      group: 'group2'
      order: 2
  create-date:
    required: false
    type: date
    filtering: RANGE
    group: 'group2'
    uiParams:
      component: date-picker
      order: 1
      showOnGrid: false
  anouncement-date:
    required: false
    type: date
    filtering: RANGE
    group: 'group2'
    uiParams:
      component: date-picker
      order: 1
      showOnGrid: false
  last-modification-date:
    required: false
    type: date
    group: 'group2'
    filtering: RANGE
    uiParams:
      component: date-picker
      order: 1
      showOnGrid: false
  city:
    type: reference
    uiParams:
      group: 'group2'
      required: false
      component: reference
      postType: city
      referenceTitleField: title
      showOnGrid: false
      gridFiltering: true
  village:
    type: reference
    uiParams:
      group: 'group2'
      required: false
      component: reference
      postType: village
      referenceTitleField: title
      showOnGrid: false
      gridFiltering: true
  document-type:
    type: reference
    uiParams:
      required: false
      group: 'group2'
      component: reference
      postType: document-type
      referenceTitleField: title
      showOnGrid: false
      gridFiltering: true
  ipotech-type:
    type: reference
    uiParams:
      required: false
      group: 'group2'
      component: reference
      postType: ipotech-type
      referenceTitleField: title
      showOnGrid: false
      gridFiltering: true
  has-internet:
    type: boolean
    uiParams:
      component: checkbox
      group: 'group3'
      order: 2
  description:
    multilingual: true
    type: string
    uiParams:
      component: editor
      inputType: text
      group: 'group3'
      order: 1
      showOnGrid: false
  address:
    multilingual: true
    type: string
    uiParams:
      component: input
      inputType: text
      group: 'group3'
      order: 1
      showOnGrid: false
  map-lng:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      group: 'group3'
      order: 1
      showOnGrid: false
  map-lat:
    multilingual: false
    type: string
    uiParams:
      component: input
      inputType: text
      group: 'group3'
      order: 1
      showOnGrid: false
  images:
    type: file
    allowedTypes: [ "jpg", "jpeg", "png" ]
    uiParams:
      required: false
      multiple: true
      group: 'group3'
      component: file
      type: image
  blueprint:
    type: file
    allowedTypes: [ "jpg", "jpeg", "png" ]
    uiParams:
      required: false
      group: 'group3'
      multiple: false
      component: file
      type: image
uiParams:
  component: post-table
  formComponent: accordion-post
  gridFiltering: true
