name: service
schema:
  title:
    multilingual: true
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  url:
    type: string
    multilingual: true
    uiParams:
      component: slug
      autoGenerateFrom: title
      order: 1
  description:
    multilingual: true
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  description2:
    type: string
    multilingual: true
    uiParams:
      component: input
      inputType: text
      order: 1
  photos:
    type: file
    allowedTypes: [ "jpg", "jpeg", "png" ]
    uiParams:
      required: false
      multiple: true
      component: file
      type: image
uiParams:
  component: post-table
