name: user
schema:
  username:
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  password:
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  email:
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
  balance:
    type: string
    uiParams:
      component: input
      inputType: text
      order: 1
      showOnGrid: true
uiParams:
  component: post-table
